[build]
  # Directory to change to before starting a build. 
  base = "frontend"

  # Directory (relative to root of your repo) that contains the deploy-ready 
  publish = "frontend/build/"

  # Default build command.
  command = "npm run build"